services:
  alertmanager-ntfy:
    image: "ghcr.io/alexbakker/alertmanager-ntfy:latest"
    volumes:
      - ./config:/config
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    ports:
      - "8000:8000"