---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-ntfy
  namespace: services
stringData:
  secret: |
    http:
      auth:
        username: "alertmanager"
        password: "superSecurePassword"
    ntfy:
      auth:
        token: "tk_************"
---
# Source: generic/templates/extraManifest.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-ntfy
data:
  config: |
    http:
      addr: :8000
    ntfy:
      baseurl: http://ntfy.services.svc.cluster.local
      notification:
        # The topic can either be a hardcoded string or a gval expression that evaluates to a string
        topic: homelab
        # Priority reference: https://docs.ntfy.sh/publish/#message-priority
        # Can either be a hardcoded string or a gval expression that evaluates to a string
        priority: |
          status == "firing" ? "urgent" : "default"
        tags:
          # Tags with no condition are always included
          # Emoji shortcode reference: https://docs.ntfy.sh/emojis/
          - tag: "+1"
            condition: status == "resolved"
          - tag: rotating_light
            condition: status == "firing"
        templates:
          title: |
            {{ if eq .Status "resolved" }}Resolved: {{ end }}{{ index .Annotations "summary" }}
          description: |
            {{ index .Annotations "description" }}
---
# Source: generic/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-ntfy
  labels:
    app.kubernetes.io/name: alertmanager-ntfy
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: alertmanager-ntfy
---
# Source: generic/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-ntfy
  labels:
    app.kubernetes.io/name: alertmanager-ntfy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager-ntfy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-ntfy
    spec:
      enableServiceLinks: false
      containers:
        - name: alertmanager-ntfy
          env:
            - name: CONFIG_FILES
              value: /config/config.yaml,/secret/secret.yaml
  
          image: "ghcr.io/alexbakker/alertmanager-ntfy:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /
              port: http
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
            - name: secret
              mountPath: /secret/
            - name: config
              mountPath: /config/
      volumes:
        - name: secret
          secret:
            items:
            - key: secret
              path: secret.yaml
            secretName: alertmanager-ntfy
        - name: config
          configMap:
            items:
            - key: config
              path: config.yaml
            name: alertmanager-ntfy