name: security
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1"
jobs:
  govulncheck:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: golang/govulncheck-action@357ea4a5418cb457db33ccd168e28f68e075eba0
        with:
          output-format: sarif
          output-file: govulncheck.sarif
      - uses: github/codeql-action/upload-sarif@64d10c13136e1c5bce3e5fbde8d4906eeaafc885
        with:
          sarif_file: govulncheck.sarif
          category: govulncheck
